language: node_js
node_js:
  - "node"

install:
    - yarn add xvfb-maybe
    - yarn install
 
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 -extension RANDR &
 
script:
    - xvfb-maybe npm test

branches:
  only: 
    - master